python main.py --task 15res  --train_dataset_path 15res/train  --dev_dataset_path 15res/dev  --test_dataset_path 15res/test  --model_name_or_path t5-base  --do_train   --do_eval  --train_batch_size 4  --gradient_accumulation_steps 4  --eval_batch_size 16  --learning_rate 3e-4  --num_train_epochs 20  --regressor True  --use_tagger True  --logger_name ablate_15res_no_contrast.txt  --log_message epoch14_4_4_3e4_0.2default --gpu_id 0 --seed 47

python main.py --task 15res  --train_dataset_path 15res/train  --dev_dataset_path 15res/dev  --test_dataset_path 15res/test  --model_name_or_path t5-base  --do_train   --do_eval  --train_batch_size 4  --gradient_accumulation_steps 4  --eval_batch_size 16  --learning_rate 3e-4  --num_train_epochs 20  --use_tagger True  --logger_name ablate_15res_no_contrast_no_regressor.txt  --log_message epoch14_4_4_3e4_0.2default --gpu_id 0 --seed 47

python main.py --task 15res  --train_dataset_path 15res/train  --dev_dataset_path 15res/dev  --test_dataset_path 15res/test  --model_name_or_path t5-base  --do_train   --do_eval  --train_batch_size 4  --gradient_accumulation_steps 4  --eval_batch_size 16  --learning_rate 3e-4  --num_train_epochs 20  --logger_name ablate_15res_no_contrast_no_regressor_no_tagger.txt  --log_message epoch14_4_4_3e4_0.2default --gpu_id 0 --seed 47

python main.py --task 16res --train_dataset_path 16res/train --dev_dataset_path 16res/dev --test_dataset_path 16res/test --model_name_or_path t5-base --do_train --do_eval --train_batch_size 4 --gradient_accumulation_steps 4 --eval_batch_size 16 --learning_rate 3e-4 --max_seq_length 256 --num_train_epochs 20 --regressor True --use_tagger True --beta 0.1   --logger_name ablate_16res_no_contrast.txt  --log_message epoch12_4_4_3e4_0.1default --gpu_id 1

python main.py --task 16res --train_dataset_path 16res/train --dev_dataset_path 16res/dev --test_dataset_path 16res/test --model_name_or_path t5-base --do_train --do_eval --train_batch_size 4 --gradient_accumulation_steps 4 --eval_batch_size 16 --learning_rate 3e-4 --max_seq_length 256 --num_train_epochs 20 --use_tagger True --beta 0.1   --logger_name ablate_16res_no_contrast_no_regressor.txt  --log_message epoch12_4_4_3e4_0.1default --gpu_id 0

python main.py --task 16res --train_dataset_path 16res/train --dev_dataset_path 16res/dev --test_dataset_path 16res/test --model_name_or_path t5-base --do_train --do_eval --train_batch_size 4 --gradient_accumulation_steps 4 --eval_batch_size 16 --learning_rate 3e-4 --max_seq_length 256 --num_train_epochs 20 --beta 0.1   --logger_name ablate_16res_no_contrast_no_regressor_no_tagger.txt  --log_message epoch12_4_4_3e4_0.1default --gpu_id 0